source 'https://rubygems.org'

gem 'cucumber', '2.3.3'
gem 'rspec'
gem 'rake'
gem 'page-object'
gem 'pretty_face'
gem 'require_all'
gem 'faker'
gem 'data_magic'
gem 'hashie'
gem 'fig_newton'
gem 'parallel_tests'
gem 'headless'
gem 'rspec-expectations'
